config/routes.rb
Rails.application.routes.draw do
  get 'homepage/index'

  root 'homepage#index'

  resources :contacts do
    post 'search', on: :collection
  end

end

app/models/contact.rb
class Contact < ActiveRecord::Base

  validates :first_name, :last_name, :phone_number, presence: { message: "Empty field!" }, allow_blank: false
  # validates :phone_number, uniqueness: true, allow_blank: false
  validates :phone_number, uniqueness: { message: "Number already in use" }
  validates :phone_number, format: { with: /\A[+]\d{1,3}\s\d{1,3}\s\d{6,}\z/, message: "Invalid phone number!" }

  # Sanitize AR find using hash conditions
  def self.search conditions
    return nil unless valid_conditions? conditions
    contacts = self.where(sanitize_sql(conditions))
    contacts
  end

  # Validate conditions hash
  def self.valid_conditions? conditions
    (conditions.keys.map{|el| el.to_sym} - fields).blank?
  end

  # Model accessible attributes
  def self.fields
    [ :first_name, :last_name, :phone_number ]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale
 
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    { :locale => I18n.locale }
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
 
  # layout "contact"

  # contacts
  # GET /contacts(.:format)
  def index
    @contacts = Contact.all
  end

  # contact
  # GET /contacts/:id(.:format)
  def show
    @contact = Contact.find(params[:id])
  end
  
  # new_contact
  # GET /contacts/new(.:format)
  def new
    @contact = Contact.new
  end

  # contacts
  # POST /contacts(.:format)
  def create
    @contact = Contact.new(contact_params)
    
    if @contact.save
      redirect_to @contact
    else
      render "new"
    end
  end

  # contact
  # PUT /contacts/:id(.:format)
  def update
    @contact = Contact.find(params[:id])
    
    if @contact.update_attributes(contact_params)
      redirect_to @contact
    else
      render "edit"
    end
  end

  # edit_contact
  # GET /contacts/:id/edit(.:format)
  def edit
    @contact = Contact.find(params[:id])
  end

  # contact
  # DELETE /contacts/:id(.:format)
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    redirect_to contacts_path
  end

  # search action
  def search
    search_param = params[:searchCriteria]
    value = params[:inputText]
    conditions = { search_param => value }
    @contacts = Contact.search conditions
    @search = true

    respond_to do |format|
      format.html { redirect_to homepage_index_path }
      # format.js { redirect_to homepage_index_path, location: @contacts }
      format.js
      format.json { render json: @contacts, status: :success, location: @contacts }
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :phone_number)
  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def index
    # @search = false
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def site_name
    # Change the value below between the quotes.
    "Phonebook"
  end

  def site_url
    if Rails.env.production?
      # Place your production URL in the quotes below
      "http://www.phonebook.com/"
    else
      # Our dev & test URL
      "http://localhost:3000"
    end
  end

  def meta_author
    # Change the value below between the quotes.
    "Giorgio Bruschini"
  end

  def meta_description
    # Change the value below between the quotes.
    "A simple phone contact manager"
  end

  def meta_keywords
    # Change the value below between the quotes.
    "Phone, Contacts, Telephone, Numbers"
  end

  # Returns the full title on a per-page basis.
  # No need to change any of this we set page_title and site_name elsewhere.
  def full_title(page_title)
    if page_title.empty?
      site_name
    else
      "#{page_title} | #{site_name}"
    end
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/layout_helper.rb
module LayoutHelper

  def bootstrap_version
    # Choose the Bootstrap version you would like to use from the CDN
    "3.3.0"
  end

end

app/views/contacts/_error_messages.html.erb
<% if contact.errors[field].any? %>
  <div class="col-sm-2">
    <div id="messages" class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <%#= contact.errors[field].join(", ") %>
      <%= contact.errors[field].first %>
    </div>
  </div>
<% end %>

app/views/contacts/_modal_confirmation.html.erb
<div class="modal fade" id="destroyConfirmation" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only"><%= t('close_modal') %></span>
        </button>
        <h4 class="modal-title"><%= t('destroy_confirmation_header_message')%></h4>
      </div>
      <div class="modal-body">
        <p><%= t('destroy_confirmation_body_message') %>?</p>
      </div>
      <div class="modal-footer">
        <%#= link_to t('confirm_button'), contact_path(), method: :delete, class: "btn btn-success" %>
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('confirm_button') %></button>
        <button type="button" class="btn btn-danger"><%= t('deny_button') %></button>
      </div>
    </div>
  </div>
</div>

app/views/contacts/edit.html.erb
<h3 class="text-center text-primary"><%= t('edit_contact')%></h3>
<div class="contact_form" id="new_contact_form">
  <%= form_for @contact, url: contact_path, html: { role: "form", class: "form-horizontal" } do |f| %>
    <div class="form-group">
      <%= f.label :first_name, class: "col-sm-4 control-label" %>
      <div class="col-sm-4">
        <%= f.text_field :first_name, class: "form-control" %>
        <%= render "error_messages", contact: @contact, field: :first_name %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :last_name, class: "col-sm-4 control-label" %>
      <div class="col-sm-4">
        <%= f.text_field :last_name, class: "form-control" %>
        <%= render "error_messages", contact: @contact, field: :first_name %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :phone_number, class: "col-sm-4 control-label" %>
      <div class="col-sm-4">
        <%= f.text_field :phone_number, class: "form-control" %>
        <%= render "error_messages", contact: @contact, field: :first_name %>
      </div>
    </div>
    <div class="col-sm-12">
      <%= f.submit t('submit'), class: "btn btn-primary col-sm-offset-5" %>
    </div>
  <% end %>
</div>

app/views/contacts/index.html.erb
<h3 class="text-center text-primary"><%= t('contacts') %></h3>
<% unless @contacts.blank? %>
  <table class="table table-responsive table-hover table-bordered contactIndex">
    <thead>
      <tr>
        <th><%= t('first_name') %></th>
        <th><%= t('last_name') %></th>
        <th><%= t('phone_number') %></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <td class="text"><%= contact.first_name %></td>
          <td class="text"><%= contact.last_name %></td>
          <td class="text"><%= contact.phone_number %></td>
          <td class="actionButtons"><%= link_to t('show'), contact_path(contact), class: "btn btn-success" %></td>
          <td class="actionButtons"><%= link_to t('edit'), edit_contact_path(contact), class: "btn btn-warning" %></td>
	  <!--<td class="actionButtons"><%#= button_tag t('destroy'), 
                                                   class: "btn btn-danger", 
                                                   data: { toggle: "modal", 
							   target: "#destroyConfirmation", 
							   contactId: contact.id } %></td>-->
	  <td class="actionButtons"><%= link_to t('destroy'), contact_path(contact),
                                        		      method: :delete,
                                        		      class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= render "modal_confirmation" %>
<% else %>
  <div class="row clearfix contacts_list_empty">
    <div class="col-md-4 column">
      <em><%= t('empty_contact_list') %></em>
    </div>
    <div class="col-md-4 column">
    </div>
    <div class="col-md-4 column">
    </div>
  </div>
<% end %>

app/views/contacts/new.html.erb
<h3 class="text-center text-primary"><%= t('new_contact')%></h3>
<%= form_for @contact, url: contacts_path, html: { role: "form", class: "form-horizontal" } do |f| %>
  <div class="form-group">
    <%= f.label t('first_name'), class: "col-sm-4 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
    <%= render "error_messages", contact: @contact, field: :first_name %>
  </div>
  <div class="form-group">
    <%= f.label t('last_name'), class: "col-sm-4 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
    <%= render "error_messages", contact: @contact, field: :last_name %>
  </div>
  <div class="form-group">
    <%= f.label t('phone_number'), class: "col-sm-4 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :phone_number, class: "form-control" %>
    </div>
    <%= render "error_messages", contact: @contact, field: :phone_number %>
  </div>
  <div class="col-sm-12 newContactSend">
    <%= f.submit t('submit'), class: "btn btn-primary col-sm-offset-5" %>
  </div>
<% end %>

app/views/contacts/search.js.erb
$('#search_results').html("<%= j render 'search/results' %>");

app/views/contacts/show.html.erb
<h3 class="text-center text-primary"><%= t('details') %></h3>
<div class="row clearfix contact-details">
  <div class="col-md-4 column">
  </div>
  <div class="col-md-4 column">
    <table class="table table-bordered contactDetails">
      <thead>
        <tr>
          <th><%= t('first_name') %></th>
          <th><%= t('last_name') %></th>
          <th><%= t('phone_number') %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="text"><%= @contact.first_name %></td>
          <td class="text"><%= @contact.last_name %></td>
          <td class="text"><%= @contact.phone_number %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="col-md-4 column">
  </div>
</div>
<%= link_to t('back_to_contacts'), contacts_path %>

app/views/homepage/index.html.erb
<h3 class="text-center text-primary"><%= t('application_name') %></h3>
<p class="text-center"><%= t('application_info') %></p>
<%= render "search/form" %>
<%= render "search/results", locals: { contacts: @contacts } %>

app/views/layouts/_footer.html.erb
<div class="container-fluid" id="footer">
  <nav class="navbar navbar-default navbar-fixed-bottom">
    <div class="navbar-inner navbar-content-center">
      <p class="muted text-center credit">
        <%= t('footer_powered_by') %>
        <%= link_to t('myself'), "https://www.linkedin.com/pub/giorgio-bruschini/36/797/857", target: "_blank" %>
        </a>
      </p>
    </div>
  </nav>
</div>

app/views/layouts/_language_switcher.html.erb
<ul class="nav navbar-nav navbar-right">
  <li>
    <% if I18n.locale == I18n.default_locale %>
      <%= link_to image_tag("italian_flag.jpg"), locale: "it" %>
    <% else %>
      <%= link_to image_tag("english_flag.png"), locale: "en" %>
    <% end %>
  </li>
</ul>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <%= image_tag "phonebook_logo.png", size: "80x80", class: "logo" %>
      </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if (current_page?(homepage_index_path) or current_page?(root_path)) %>">
          <%= link_to t('homepage'), homepage_index_path %>
        </li>
        <li class="<%= 'active' if current_page?(contacts_path) %>">
          <%= link_to t('contacts'), contacts_path %>
        </li>
        <li class="<%= 'active' if current_page?(new_contact_path) %>">
          <%= link_to t('new_contact'), new_contact_path %>
        </li>
      </ul>
      <%= render "layouts/language_switcher" %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="<%= meta_description %>">
  <meta name="author" content="<%= meta_author %>">
  <meta name="Keywords" content="<%= meta_keywords %>">
  <title><%= full_title(yield(:title)) %></title>
  <link href="//netdna.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
</head>
<body>
  <div class="container-fluid" id="main">
    <div class="row clearfix">
      <div class="col-md-12 column">
        <%= render "layouts/navbar" %>
        <%= yield %>
      </div>
    </div>
  </div>
  <%= render "layouts/footer" %>
  <script src="//netdna.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/js/bootstrap.min.js"></script>
</body>
</html>

app/views/layouts/contact.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <%= yield %>
    </div>
  </div>
</div>

app/views/search/_form.html.erb
<h3 class="text-center text-muted">
  <%= t('search_contact') %>
</h3>
<%= form_tag search_contacts_path, remote: :true, class: "form-horizontal", role:"form" do %>
  <div class="form-group">
    <div class="col-sm-2">
      <label for="searchCriteria" class="control-label col-sm-offset-4"><%= t('search_by') %></label>
    </div>
    <div class="col-sm-4 selectContainer">
      <% select_options = [ [t('first_name'), :first_name], 
                            [t('last_name'), :last_name], 
                            [t('phone_number'), :phone_number] 
                          ] %>
      <%= select_tag "searchCriteria", options_for_select(select_options), { class: "form-control" } %>
    </div>
    <div class="col-sm-4">
      <%= text_field_tag "inputText", nil, class: "form-control" %>  
    </div>
    <div class="col-sm-2">
      <%= submit_tag t('search'), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/search/_results.html.erb
<div id="search_results">
<% unless @contacts.blank? %>
  <h3 class="text-center text-info"><%= t('results') %></h3>
  <table class="table table-bordered searchResults">
    <thead>
      <tr>
        <th><%= t('first_name')%></th>
        <th><%= t('last_name') %></th>
        <th><%= t('phone_number') %></th>
        <th></th>
	<th></th>
	<th></th>
      </tr>
    </thead>
    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <td class="text"><%= contact.first_name %></td>
          <td class="text"><%= contact.last_name %></td>
          <td class="text"><%= contact.phone_number %></td>
          <td class="actionButtons"><%= link_to t('show'), contact_path(contact), class: "btn btn-success" %></td>
          <td class="actionButtons"><%= link_to t('edit'), edit_contact_path(contact), class: "btn btn-warning" %></td>
          <td class="actionButtons"><%= link_to t('destroy'), contact_path(contact),
                                        method: :delete,
                    			class: "btn btn-danger",
                                        data: { confirm: t('destroy_confirmation') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <% if @search %>
    <div class="row clearfix">
      <h3 class="text-center text-info"><%= t('no_results_found') %></h3>
    </div>
  <% end %>
<% end %>
</div>